
version: "3"

services:
    postgredb:
        restart: always
        image: postgres
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: alex
            POSTGRES_DB: propulse
    pgadmin:
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: alex
        ports:
             - 5050:5050
    frontend:
        build: .
        ports:
            - 3000:3000
        depends_on:
            - postgredb
        
volumes:
    db-data:
